[tool.poetry]
name = "library"
version = "0.1.0"
description = ""
authors = ["goncharoman <goncharoman@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
apiflask = {extras = ["yaml"], version = "^1.3.0"}
sqlalchemy = "^2.0.7"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
mypy = "^1.1.1"
flake8 = "^6.0.0"
pytest = "^7.2.2"
isort = "^5.12.0"
flake8-comprehensions = "^3.11.1"
flake8-bugbear = "^23.3.23"
flake8-quotes = "^3.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
